version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data  
    depends_on:
      - redis
    env_file:
      - .env
    

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.local  
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - web
