version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data  
    depends_on:
      - redis
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '6'

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
