version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: ${REDIS_PASSWORD}  
      FASTAPI_HOST: 0.0.0.0
      FASTAPI_PORT: 8000
      OPENAI_API_KEY: ${OPENAI_API_KEY}  

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
